name: HomeGUI
version: 1.1.2
author: TechnoVision
main: com.technovision.homegui.Main
api-version: 1.13
depend: [Essentials]

commands:
  home:
    description: Opens the HomeGUI screen.
    usage: /<command>
    aliases: homes
  h:
    description: Reloads the HomeGUI config.
    usage: /<command>